// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: plugins/action.proto

package plugins

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SSPId        string `protobuf:"bytes,1,opt,name=SSPId,proto3" json:"SSPId,omitempty"`
	ControlId    string `protobuf:"bytes,2,opt,name=ControlId,proto3" json:"ControlId,omitempty"`
	ComponentId  string `protobuf:"bytes,3,opt,name=ComponentId,proto3" json:"ComponentId,omitempty"`
	AssessmentID string `protobuf:"bytes,4,opt,name=AssessmentID,proto3" json:"AssessmentID,omitempty"`
}

func (x *ActionInput) Reset() {
	*x = ActionInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugins_action_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionInput) ProtoMessage() {}

func (x *ActionInput) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_action_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionInput.ProtoReflect.Descriptor instead.
func (*ActionInput) Descriptor() ([]byte, []int) {
	return file_plugins_action_proto_rawDescGZIP(), []int{0}
}

func (x *ActionInput) GetSSPId() string {
	if x != nil {
		return x.SSPId
	}
	return ""
}

func (x *ActionInput) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *ActionInput) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *ActionInput) GetAssessmentID() string {
	if x != nil {
		return x.AssessmentID
	}
	return ""
}

type ActionOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SSPId        string `protobuf:"bytes,1,opt,name=SSPId,proto3" json:"SSPId,omitempty"`
	ControlId    string `protobuf:"bytes,2,opt,name=ControlId,proto3" json:"ControlId,omitempty"`
	ComponentId  string `protobuf:"bytes,3,opt,name=ComponentId,proto3" json:"ComponentId,omitempty"`
	AssessmentID string `protobuf:"bytes,4,opt,name=AssessmentID,proto3" json:"AssessmentID,omitempty"`
	Compliant    bool   `protobuf:"varint,5,opt,name=Compliant,proto3" json:"Compliant,omitempty"`
}

func (x *ActionOutput) Reset() {
	*x = ActionOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugins_action_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionOutput) ProtoMessage() {}

func (x *ActionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_action_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionOutput.ProtoReflect.Descriptor instead.
func (*ActionOutput) Descriptor() ([]byte, []int) {
	return file_plugins_action_proto_rawDescGZIP(), []int{1}
}

func (x *ActionOutput) GetSSPId() string {
	if x != nil {
		return x.SSPId
	}
	return ""
}

func (x *ActionOutput) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *ActionOutput) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *ActionOutput) GetAssessmentID() string {
	if x != nil {
		return x.AssessmentID
	}
	return ""
}

func (x *ActionOutput) GetCompliant() bool {
	if x != nil {
		return x.Compliant
	}
	return false
}

var File_plugins_action_proto protoreflect.FileDescriptor

var file_plugins_action_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x22, 0x87,
	0x01, 0x0a, 0x0b, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x53, 0x53, 0x50, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53,
	0x53, 0x50, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x41, 0x73, 0x73, 0x65,
	0x73, 0x73, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0xa6, 0x01, 0x0a, 0x0c, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x53, 0x50,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x53, 0x50, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x22, 0x0a, 0x0c, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e,
	0x74, 0x32, 0x45, 0x0a, 0x0d, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x13, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugins_action_proto_rawDescOnce sync.Once
	file_plugins_action_proto_rawDescData = file_plugins_action_proto_rawDesc
)

func file_plugins_action_proto_rawDescGZIP() []byte {
	file_plugins_action_proto_rawDescOnce.Do(func() {
		file_plugins_action_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugins_action_proto_rawDescData)
	})
	return file_plugins_action_proto_rawDescData
}

var file_plugins_action_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugins_action_proto_goTypes = []interface{}{
	(*ActionInput)(nil),  // 0: plugin.ActionInput
	(*ActionOutput)(nil), // 1: plugin.ActionOutput
}
var file_plugins_action_proto_depIdxs = []int32{
	0, // 0: plugin.ActionService.Execute:input_type -> plugin.ActionInput
	1, // 1: plugin.ActionService.Execute:output_type -> plugin.ActionOutput
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugins_action_proto_init() }
func file_plugins_action_proto_init() {
	if File_plugins_action_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plugins_action_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugins_action_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugins_action_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugins_action_proto_goTypes,
		DependencyIndexes: file_plugins_action_proto_depIdxs,
		MessageInfos:      file_plugins_action_proto_msgTypes,
	}.Build()
	File_plugins_action_proto = out.File
	file_plugins_action_proto_rawDesc = nil
	file_plugins_action_proto_goTypes = nil
	file_plugins_action_proto_depIdxs = nil
}
