name: test-build
run-name: ${{ github.actor }} test job
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the docker-compose stack
        run: cd test && docker-compose -f docker-compose.yml up -d
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      - name: Check running containers
        run: docker ps -a
